#!/bin/bash

# todo: ping
# change & to whitespace at ENV_FILE_NAME

function help {
  echo "usage:"
  echo " ${0} env_name [-p]"
  exit 1
}

function print_envs {
  if [ $# -gt 0 ]; then
    grep "$1" ${ENV_FILE_NAME}
  else
    cat ${ENV_FILE_NAME}
  fi
  exit 0
}

if [ $# = 0 ]; then
  help
fi

PORT=22
PARAMS=""
PRINT=""
ENV_FILE_NAME="${HOME}/bin/.env.srv"

while [ $# -gt 0 ]; do
  if [ "$1" = "-p" ]; then
    PARAMS="true"
  elif [ "$1" = "print" ]; then
    PRINT="true"
  else
    ENV_NAME="$1"
  fi
  shift
done

if [ "${PRINT}" != "" ]; then
  print_envs ${ENV_NAME}
fi

ENV_FILE=`grep "^[^#;]" ${ENV_FILE_NAME}`
IFS=$'\n'
ENV_ENTRIES=(${ENV_FILE})
IFS=' '

for ENV in "${ENV_ENTRIES[@]}"
do
  ENTRY=(${ENV})
  if [ "${ENTRY[1]}" = "${ENV_NAME}" ]; then
    if [ "${ENTRY[4]}" != "" ]; then
      PORT=${ENTRY[4]}
    fi
    if [ "${PARAMS}" != "" ]; then
      if [ "${ENTRY[5]}" = "" ]; then
        echo "Parameters for ${ENV} not specifiled in ${ENV_FILE_NAME}!"
        exit 3
      fi
    fi
    echo ssh "${ENTRY[3]}"@"${ENTRY[2]}" -p ${PORT} ${PARAMS}
    ssh "${ENTRY[3]}"@"${ENTRY[2]}" -p ${PORT} ${PARAMS}
    exit 0
  fi
done

echo Environment not found!

exit 2

