#!/bin/bash

function colored()
{
  # $1 color number, $@ text
  COLOR=$1
  shift
  TEXT=$@
  printf "\e[${COLOR}m${TEXT}\e[0m";
}

REMOTES=$(git remote)

echo "Found following remotes: `echo ${REMOTES} | tr '\r\n' ' '`"

for REMOTE in ${REMOTES}
do
  COMMAND="git push ${REMOTE} $@"
  echo;
  echo $(colored 33 ${COMMAND})
  eval ${COMMAND}
done

