#!/usr/bin/env bash
#tmux new-session \; new-window \; select-window -t :1 \; split-window \; select-pane -U \; split-window -h \; new-window \; select-window -t :2 \; split-window \; split-window -h \; select-pane -U \; split-window -h \; select-window -t :1
tmux new-session \; new-window \; select-window -t :1 \; split-window \; select-pane -U \; split-window -h \; select-pane -D \; new-window \; select-window -t :2 \; split-window \; split-window -h \; select-pane -U \; split-window -h \; select-window -t :1
